
-- CREAR LA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS concesionario;

-- USAR LA BBDD
USE concesionario;

-- CREAR TABLA COCHE
CREATE TABLE IF NOT EXISTS coche (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	matricula VARCHAR(7) UNIQUE NOT NULL,
	marca VARCHAR(15),
	modelo VARCHAR(15),
	precio_base FLOAT NOT NULL,
	ultima_revision DATE
);


-- CREAR TABLA CLIENTE
CREATE TABLE IF NOT EXISTS cliente (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(20) NOT NULL,
	dni VARCHAR(9) UNIQUE NOT NULL,
	edad INT,
	es_premium BOOLEAN DEFAULT FALSE,
	fecha_alta DATE
);


-- CREAR TABLA VENTA
CREATE TABLE IF NOT EXISTS venta (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	codigo_factura VARCHAR(6) NOT NULL,
	fecha_venta DATE,
	precio_final INT NOT NULL,
	garantia INT,
	es_financiado BOOLEAN DEFAULT FALSE,
	id_coche INT UNSIGNED NOT NULL,
	FOREIGN KEY (id_coche) REFERENCES coche(id) ON DELETE CASCADE,
	id_cliente INT UNSIGNED NOT NULL,
	FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE
);
